title: Elias Vaara
logo: assets/logo2.png
remote_theme: pages-themes/minimal@v0.2.0
url: eliasvaa.github.io
plugins:
- jekyll-remote-theme 

head:
- <link rel="stylesheet"  href="/assets/css/style.css">
