title: Elias Vaara
logo: assets\1738166325527.jpg
remote_theme: pages-themes/minimal@v0.2.0
url: eliasvaa.github.io
plugins:
- jekyll-remote-theme 

include:
  - _includes/head-custom.html


head:
- <link rel="stylesheet" href="/assets/css/style.css">


